### ISSUE TITLE
Compilation is broken since 49632b8

### ISSUE THREAD

**Issue by lcd047** [jonas/tig#248]
As per the title:

```
gcc -I. -Iinclude -g -O2 -MMD -MP -MF .deps/src/tig.d -DHAVE_CONFIG_H '-DTIG_VERSION="1.2.1-156-g49632b8"' '-DSYSCONFDIR="/usr/local/etc"'  -c -o src/tig.o src/tig.c
In file included from src/tig.c:16:0:
include/tig/tig.h:18:24: fatal error: tig/config.h: No such file or directory
 #include "tig/config.h"
                        ^
compilation terminated.
make: *** [src/tig.o] Error 1
```
