### ISSUE TITLE
Does not build with glibc-2.5

### ISSUE THREAD

**Issue by bbannier** [jonas/tig#152]
Hi,

after a0fdac2975ce8cf2de07435c7a3c6ccc1415393c I cannot build and link tig anymore under Scientific Linux 5.3 which comes with glibc-2.5. I see

```
cc -Wall -O2 '-DTIG_VERSION="1.1-66-gf0ad1f7"' '-DSYSCONFDIR="/phenix/u/bbannier/etc"'  -c -o tig.o tig.c
In file included from tig.c:14:
tig.h:73:4: warning: #warning SysV or X/Open-compatible Curses installation is required.
tig.h:74:4: warning: #warning Will assume Curses is found in default include and library path.
tig.h:75:4: warning: #warning To fix any build issues please use autotools to configure Curses.
tig.h:76:4: warning: #warning See INSTALL file for instructions.
tig.c: In function ‘open_blob_editor’:
tig.c:5327: warning: implicit declaration of function ‘mkstemps’
cc -Wall -O2 '-DTIG_VERSION="1.1-66-gf0ad1f7"' '-DSYSCONFDIR="/phenix/u/bbannier/etc"'  -c -o io.o io.c
In file included from io.c:14:
tig.h:73:4: warning: #warning SysV or X/Open-compatible Curses installation is required.
tig.h:74:4: warning: #warning Will assume Curses is found in default include and library path.
tig.h:75:4: warning: #warning To fix any build issues please use autotools to configure Curses.
tig.h:76:4: warning: #warning See INSTALL file for instructions.
cc -Wall -O2 '-DTIG_VERSION="1.1-66-gf0ad1f7"' '-DSYSCONFDIR="/phenix/u/bbannier/etc"'  -c -o graph.o graph.c
In file included from graph.c:14:
tig.h:73:4: warning: #warning SysV or X/Open-compatible Curses installation is required.
tig.h:74:4: warning: #warning Will assume Curses is found in default include and library path.
tig.h:75:4: warning: #warning To fix any build issues please use autotools to configure Curses.
tig.h:76:4: warning: #warning See INSTALL file for instructions.
cc -Wall -O2 '-DTIG_VERSION="1.1-66-gf0ad1f7"' '-DSYSCONFDIR="/phenix/u/bbannier/etc"'  -c -o refs.o refs.c
In file included from refs.c:14:
tig.h:73:4: warning: #warning SysV or X/Open-compatible Curses installation is required.
tig.h:74:4: warning: #warning Will assume Curses is found in default include and library path.
tig.h:75:4: warning: #warning To fix any build issues please use autotools to configure Curses.
tig.h:76:4: warning: #warning See INSTALL file for instructions.
cc   tig.o io.o graph.o refs.o  -lcurses -o tig
tig.o: In function `open_blob_editor':
tig.c:(.text+0x77d7): undefined reference to `mkstemps'
collect2: ld returned 1 exit status
make: *** [tig] Error 1
```

This builds fine on another machine with glibc-2.17 btw.

Could you choose an implementation which works with older glibc as well?
